# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.17

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/Cellar/cmake/3.17.3/bin/cmake

# The command to remove a file.
RM = /usr/local/Cellar/cmake/3.17.3/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/markcao/Documents/Github_Codes/momo

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/markcao/Documents/Github_Codes/momo

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/local/Cellar/cmake/3.17.3/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/local/Cellar/cmake/3.17.3/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/markcao/Documents/Github_Codes/momo/CMakeFiles /Users/markcao/Documents/Github_Codes/momo/CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/markcao/Documents/Github_Codes/momo/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named momo

# Build rule for target.
momo: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 momo
.PHONY : momo

# fast build rule for target.
momo/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/build
.PHONY : momo/fast

src/ayame/ayame_client.o: src/ayame/ayame_client.cpp.o

.PHONY : src/ayame/ayame_client.o

# target to build an object file
src/ayame/ayame_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/ayame/ayame_client.cpp.o
.PHONY : src/ayame/ayame_client.cpp.o

src/ayame/ayame_client.i: src/ayame/ayame_client.cpp.i

.PHONY : src/ayame/ayame_client.i

# target to preprocess a source file
src/ayame/ayame_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/ayame/ayame_client.cpp.i
.PHONY : src/ayame/ayame_client.cpp.i

src/ayame/ayame_client.s: src/ayame/ayame_client.cpp.s

.PHONY : src/ayame/ayame_client.s

# target to generate assembly for a file
src/ayame/ayame_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/ayame/ayame_client.cpp.s
.PHONY : src/ayame/ayame_client.cpp.s

src/mac_helper/mac_capturer.o: src/mac_helper/mac_capturer.mm.o

.PHONY : src/mac_helper/mac_capturer.o

# target to build an object file
src/mac_helper/mac_capturer.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/mac_helper/mac_capturer.mm.o
.PHONY : src/mac_helper/mac_capturer.mm.o

src/mac_helper/mac_capturer.i: src/mac_helper/mac_capturer.mm.i

.PHONY : src/mac_helper/mac_capturer.i

# target to preprocess a source file
src/mac_helper/mac_capturer.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/mac_helper/mac_capturer.mm.i
.PHONY : src/mac_helper/mac_capturer.mm.i

src/mac_helper/mac_capturer.s: src/mac_helper/mac_capturer.mm.s

.PHONY : src/mac_helper/mac_capturer.s

# target to generate assembly for a file
src/mac_helper/mac_capturer.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/mac_helper/mac_capturer.mm.s
.PHONY : src/mac_helper/mac_capturer.mm.s

src/mac_helper/macos_version.o: src/mac_helper/macos_version.mm.o

.PHONY : src/mac_helper/macos_version.o

# target to build an object file
src/mac_helper/macos_version.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/mac_helper/macos_version.mm.o
.PHONY : src/mac_helper/macos_version.mm.o

src/mac_helper/macos_version.i: src/mac_helper/macos_version.mm.i

.PHONY : src/mac_helper/macos_version.i

# target to preprocess a source file
src/mac_helper/macos_version.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/mac_helper/macos_version.mm.i
.PHONY : src/mac_helper/macos_version.mm.i

src/mac_helper/macos_version.s: src/mac_helper/macos_version.mm.s

.PHONY : src/mac_helper/macos_version.s

# target to generate assembly for a file
src/mac_helper/macos_version.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/mac_helper/macos_version.mm.s
.PHONY : src/mac_helper/macos_version.mm.s

src/mac_helper/objc_codec_factory_helper.o: src/mac_helper/objc_codec_factory_helper.mm.o

.PHONY : src/mac_helper/objc_codec_factory_helper.o

# target to build an object file
src/mac_helper/objc_codec_factory_helper.mm.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/mac_helper/objc_codec_factory_helper.mm.o
.PHONY : src/mac_helper/objc_codec_factory_helper.mm.o

src/mac_helper/objc_codec_factory_helper.i: src/mac_helper/objc_codec_factory_helper.mm.i

.PHONY : src/mac_helper/objc_codec_factory_helper.i

# target to preprocess a source file
src/mac_helper/objc_codec_factory_helper.mm.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/mac_helper/objc_codec_factory_helper.mm.i
.PHONY : src/mac_helper/objc_codec_factory_helper.mm.i

src/mac_helper/objc_codec_factory_helper.s: src/mac_helper/objc_codec_factory_helper.mm.s

.PHONY : src/mac_helper/objc_codec_factory_helper.s

# target to generate assembly for a file
src/mac_helper/objc_codec_factory_helper.mm.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/mac_helper/objc_codec_factory_helper.mm.s
.PHONY : src/mac_helper/objc_codec_factory_helper.mm.s

src/main.o: src/main.cpp.o

.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/momo_version.o: src/momo_version.cpp.o

.PHONY : src/momo_version.o

# target to build an object file
src/momo_version.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/momo_version.cpp.o
.PHONY : src/momo_version.cpp.o

src/momo_version.i: src/momo_version.cpp.i

.PHONY : src/momo_version.i

# target to preprocess a source file
src/momo_version.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/momo_version.cpp.i
.PHONY : src/momo_version.cpp.i

src/momo_version.s: src/momo_version.cpp.s

.PHONY : src/momo_version.s

# target to generate assembly for a file
src/momo_version.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/momo_version.cpp.s
.PHONY : src/momo_version.cpp.s

src/p2p/p2p_server.o: src/p2p/p2p_server.cpp.o

.PHONY : src/p2p/p2p_server.o

# target to build an object file
src/p2p/p2p_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/p2p/p2p_server.cpp.o
.PHONY : src/p2p/p2p_server.cpp.o

src/p2p/p2p_server.i: src/p2p/p2p_server.cpp.i

.PHONY : src/p2p/p2p_server.i

# target to preprocess a source file
src/p2p/p2p_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/p2p/p2p_server.cpp.i
.PHONY : src/p2p/p2p_server.cpp.i

src/p2p/p2p_server.s: src/p2p/p2p_server.cpp.s

.PHONY : src/p2p/p2p_server.s

# target to generate assembly for a file
src/p2p/p2p_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/p2p/p2p_server.cpp.s
.PHONY : src/p2p/p2p_server.cpp.s

src/p2p/p2p_session.o: src/p2p/p2p_session.cpp.o

.PHONY : src/p2p/p2p_session.o

# target to build an object file
src/p2p/p2p_session.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/p2p/p2p_session.cpp.o
.PHONY : src/p2p/p2p_session.cpp.o

src/p2p/p2p_session.i: src/p2p/p2p_session.cpp.i

.PHONY : src/p2p/p2p_session.i

# target to preprocess a source file
src/p2p/p2p_session.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/p2p/p2p_session.cpp.i
.PHONY : src/p2p/p2p_session.cpp.i

src/p2p/p2p_session.s: src/p2p/p2p_session.cpp.s

.PHONY : src/p2p/p2p_session.s

# target to generate assembly for a file
src/p2p/p2p_session.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/p2p/p2p_session.cpp.s
.PHONY : src/p2p/p2p_session.cpp.s

src/p2p/p2p_websocket_session.o: src/p2p/p2p_websocket_session.cpp.o

.PHONY : src/p2p/p2p_websocket_session.o

# target to build an object file
src/p2p/p2p_websocket_session.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/p2p/p2p_websocket_session.cpp.o
.PHONY : src/p2p/p2p_websocket_session.cpp.o

src/p2p/p2p_websocket_session.i: src/p2p/p2p_websocket_session.cpp.i

.PHONY : src/p2p/p2p_websocket_session.i

# target to preprocess a source file
src/p2p/p2p_websocket_session.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/p2p/p2p_websocket_session.cpp.i
.PHONY : src/p2p/p2p_websocket_session.cpp.i

src/p2p/p2p_websocket_session.s: src/p2p/p2p_websocket_session.cpp.s

.PHONY : src/p2p/p2p_websocket_session.s

# target to generate assembly for a file
src/p2p/p2p_websocket_session.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/p2p/p2p_websocket_session.cpp.s
.PHONY : src/p2p/p2p_websocket_session.cpp.s

src/rtc/device_video_capturer.o: src/rtc/device_video_capturer.cpp.o

.PHONY : src/rtc/device_video_capturer.o

# target to build an object file
src/rtc/device_video_capturer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/device_video_capturer.cpp.o
.PHONY : src/rtc/device_video_capturer.cpp.o

src/rtc/device_video_capturer.i: src/rtc/device_video_capturer.cpp.i

.PHONY : src/rtc/device_video_capturer.i

# target to preprocess a source file
src/rtc/device_video_capturer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/device_video_capturer.cpp.i
.PHONY : src/rtc/device_video_capturer.cpp.i

src/rtc/device_video_capturer.s: src/rtc/device_video_capturer.cpp.s

.PHONY : src/rtc/device_video_capturer.s

# target to generate assembly for a file
src/rtc/device_video_capturer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/device_video_capturer.cpp.s
.PHONY : src/rtc/device_video_capturer.cpp.s

src/rtc/h264_format.o: src/rtc/h264_format.cpp.o

.PHONY : src/rtc/h264_format.o

# target to build an object file
src/rtc/h264_format.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/h264_format.cpp.o
.PHONY : src/rtc/h264_format.cpp.o

src/rtc/h264_format.i: src/rtc/h264_format.cpp.i

.PHONY : src/rtc/h264_format.i

# target to preprocess a source file
src/rtc/h264_format.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/h264_format.cpp.i
.PHONY : src/rtc/h264_format.cpp.i

src/rtc/h264_format.s: src/rtc/h264_format.cpp.s

.PHONY : src/rtc/h264_format.s

# target to generate assembly for a file
src/rtc/h264_format.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/h264_format.cpp.s
.PHONY : src/rtc/h264_format.cpp.s

src/rtc/momo_video_decoder_factory.o: src/rtc/momo_video_decoder_factory.cpp.o

.PHONY : src/rtc/momo_video_decoder_factory.o

# target to build an object file
src/rtc/momo_video_decoder_factory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/momo_video_decoder_factory.cpp.o
.PHONY : src/rtc/momo_video_decoder_factory.cpp.o

src/rtc/momo_video_decoder_factory.i: src/rtc/momo_video_decoder_factory.cpp.i

.PHONY : src/rtc/momo_video_decoder_factory.i

# target to preprocess a source file
src/rtc/momo_video_decoder_factory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/momo_video_decoder_factory.cpp.i
.PHONY : src/rtc/momo_video_decoder_factory.cpp.i

src/rtc/momo_video_decoder_factory.s: src/rtc/momo_video_decoder_factory.cpp.s

.PHONY : src/rtc/momo_video_decoder_factory.s

# target to generate assembly for a file
src/rtc/momo_video_decoder_factory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/momo_video_decoder_factory.cpp.s
.PHONY : src/rtc/momo_video_decoder_factory.cpp.s

src/rtc/momo_video_encoder_factory.o: src/rtc/momo_video_encoder_factory.cpp.o

.PHONY : src/rtc/momo_video_encoder_factory.o

# target to build an object file
src/rtc/momo_video_encoder_factory.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/momo_video_encoder_factory.cpp.o
.PHONY : src/rtc/momo_video_encoder_factory.cpp.o

src/rtc/momo_video_encoder_factory.i: src/rtc/momo_video_encoder_factory.cpp.i

.PHONY : src/rtc/momo_video_encoder_factory.i

# target to preprocess a source file
src/rtc/momo_video_encoder_factory.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/momo_video_encoder_factory.cpp.i
.PHONY : src/rtc/momo_video_encoder_factory.cpp.i

src/rtc/momo_video_encoder_factory.s: src/rtc/momo_video_encoder_factory.cpp.s

.PHONY : src/rtc/momo_video_encoder_factory.s

# target to generate assembly for a file
src/rtc/momo_video_encoder_factory.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/momo_video_encoder_factory.cpp.s
.PHONY : src/rtc/momo_video_encoder_factory.cpp.s

src/rtc/native_buffer.o: src/rtc/native_buffer.cpp.o

.PHONY : src/rtc/native_buffer.o

# target to build an object file
src/rtc/native_buffer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/native_buffer.cpp.o
.PHONY : src/rtc/native_buffer.cpp.o

src/rtc/native_buffer.i: src/rtc/native_buffer.cpp.i

.PHONY : src/rtc/native_buffer.i

# target to preprocess a source file
src/rtc/native_buffer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/native_buffer.cpp.i
.PHONY : src/rtc/native_buffer.cpp.i

src/rtc/native_buffer.s: src/rtc/native_buffer.cpp.s

.PHONY : src/rtc/native_buffer.s

# target to generate assembly for a file
src/rtc/native_buffer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/native_buffer.cpp.s
.PHONY : src/rtc/native_buffer.cpp.s

src/rtc/peer_connection_observer.o: src/rtc/peer_connection_observer.cpp.o

.PHONY : src/rtc/peer_connection_observer.o

# target to build an object file
src/rtc/peer_connection_observer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/peer_connection_observer.cpp.o
.PHONY : src/rtc/peer_connection_observer.cpp.o

src/rtc/peer_connection_observer.i: src/rtc/peer_connection_observer.cpp.i

.PHONY : src/rtc/peer_connection_observer.i

# target to preprocess a source file
src/rtc/peer_connection_observer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/peer_connection_observer.cpp.i
.PHONY : src/rtc/peer_connection_observer.cpp.i

src/rtc/peer_connection_observer.s: src/rtc/peer_connection_observer.cpp.s

.PHONY : src/rtc/peer_connection_observer.s

# target to generate assembly for a file
src/rtc/peer_connection_observer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/peer_connection_observer.cpp.s
.PHONY : src/rtc/peer_connection_observer.cpp.s

src/rtc/rtc_connection.o: src/rtc/rtc_connection.cpp.o

.PHONY : src/rtc/rtc_connection.o

# target to build an object file
src/rtc/rtc_connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/rtc_connection.cpp.o
.PHONY : src/rtc/rtc_connection.cpp.o

src/rtc/rtc_connection.i: src/rtc/rtc_connection.cpp.i

.PHONY : src/rtc/rtc_connection.i

# target to preprocess a source file
src/rtc/rtc_connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/rtc_connection.cpp.i
.PHONY : src/rtc/rtc_connection.cpp.i

src/rtc/rtc_connection.s: src/rtc/rtc_connection.cpp.s

.PHONY : src/rtc/rtc_connection.s

# target to generate assembly for a file
src/rtc/rtc_connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/rtc_connection.cpp.s
.PHONY : src/rtc/rtc_connection.cpp.s

src/rtc/rtc_manager.o: src/rtc/rtc_manager.cpp.o

.PHONY : src/rtc/rtc_manager.o

# target to build an object file
src/rtc/rtc_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/rtc_manager.cpp.o
.PHONY : src/rtc/rtc_manager.cpp.o

src/rtc/rtc_manager.i: src/rtc/rtc_manager.cpp.i

.PHONY : src/rtc/rtc_manager.i

# target to preprocess a source file
src/rtc/rtc_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/rtc_manager.cpp.i
.PHONY : src/rtc/rtc_manager.cpp.i

src/rtc/rtc_manager.s: src/rtc/rtc_manager.cpp.s

.PHONY : src/rtc/rtc_manager.s

# target to generate assembly for a file
src/rtc/rtc_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/rtc_manager.cpp.s
.PHONY : src/rtc/rtc_manager.cpp.s

src/rtc/rtc_ssl_verifier.o: src/rtc/rtc_ssl_verifier.cpp.o

.PHONY : src/rtc/rtc_ssl_verifier.o

# target to build an object file
src/rtc/rtc_ssl_verifier.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/rtc_ssl_verifier.cpp.o
.PHONY : src/rtc/rtc_ssl_verifier.cpp.o

src/rtc/rtc_ssl_verifier.i: src/rtc/rtc_ssl_verifier.cpp.i

.PHONY : src/rtc/rtc_ssl_verifier.i

# target to preprocess a source file
src/rtc/rtc_ssl_verifier.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/rtc_ssl_verifier.cpp.i
.PHONY : src/rtc/rtc_ssl_verifier.cpp.i

src/rtc/rtc_ssl_verifier.s: src/rtc/rtc_ssl_verifier.cpp.s

.PHONY : src/rtc/rtc_ssl_verifier.s

# target to generate assembly for a file
src/rtc/rtc_ssl_verifier.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/rtc_ssl_verifier.cpp.s
.PHONY : src/rtc/rtc_ssl_verifier.cpp.s

src/rtc/scalable_track_source.o: src/rtc/scalable_track_source.cpp.o

.PHONY : src/rtc/scalable_track_source.o

# target to build an object file
src/rtc/scalable_track_source.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/scalable_track_source.cpp.o
.PHONY : src/rtc/scalable_track_source.cpp.o

src/rtc/scalable_track_source.i: src/rtc/scalable_track_source.cpp.i

.PHONY : src/rtc/scalable_track_source.i

# target to preprocess a source file
src/rtc/scalable_track_source.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/scalable_track_source.cpp.i
.PHONY : src/rtc/scalable_track_source.cpp.i

src/rtc/scalable_track_source.s: src/rtc/scalable_track_source.cpp.s

.PHONY : src/rtc/scalable_track_source.s

# target to generate assembly for a file
src/rtc/scalable_track_source.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/scalable_track_source.cpp.s
.PHONY : src/rtc/scalable_track_source.cpp.s

src/rtc/screen_video_capturer.o: src/rtc/screen_video_capturer.cpp.o

.PHONY : src/rtc/screen_video_capturer.o

# target to build an object file
src/rtc/screen_video_capturer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/screen_video_capturer.cpp.o
.PHONY : src/rtc/screen_video_capturer.cpp.o

src/rtc/screen_video_capturer.i: src/rtc/screen_video_capturer.cpp.i

.PHONY : src/rtc/screen_video_capturer.i

# target to preprocess a source file
src/rtc/screen_video_capturer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/screen_video_capturer.cpp.i
.PHONY : src/rtc/screen_video_capturer.cpp.i

src/rtc/screen_video_capturer.s: src/rtc/screen_video_capturer.cpp.s

.PHONY : src/rtc/screen_video_capturer.s

# target to generate assembly for a file
src/rtc/screen_video_capturer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/rtc/screen_video_capturer.cpp.s
.PHONY : src/rtc/screen_video_capturer.cpp.s

src/sdl_renderer/sdl_renderer.o: src/sdl_renderer/sdl_renderer.cpp.o

.PHONY : src/sdl_renderer/sdl_renderer.o

# target to build an object file
src/sdl_renderer/sdl_renderer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/sdl_renderer/sdl_renderer.cpp.o
.PHONY : src/sdl_renderer/sdl_renderer.cpp.o

src/sdl_renderer/sdl_renderer.i: src/sdl_renderer/sdl_renderer.cpp.i

.PHONY : src/sdl_renderer/sdl_renderer.i

# target to preprocess a source file
src/sdl_renderer/sdl_renderer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/sdl_renderer/sdl_renderer.cpp.i
.PHONY : src/sdl_renderer/sdl_renderer.cpp.i

src/sdl_renderer/sdl_renderer.s: src/sdl_renderer/sdl_renderer.cpp.s

.PHONY : src/sdl_renderer/sdl_renderer.s

# target to generate assembly for a file
src/sdl_renderer/sdl_renderer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/sdl_renderer/sdl_renderer.cpp.s
.PHONY : src/sdl_renderer/sdl_renderer.cpp.s

src/serial_data_channel/serial_data_channel.o: src/serial_data_channel/serial_data_channel.cpp.o

.PHONY : src/serial_data_channel/serial_data_channel.o

# target to build an object file
src/serial_data_channel/serial_data_channel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/serial_data_channel/serial_data_channel.cpp.o
.PHONY : src/serial_data_channel/serial_data_channel.cpp.o

src/serial_data_channel/serial_data_channel.i: src/serial_data_channel/serial_data_channel.cpp.i

.PHONY : src/serial_data_channel/serial_data_channel.i

# target to preprocess a source file
src/serial_data_channel/serial_data_channel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/serial_data_channel/serial_data_channel.cpp.i
.PHONY : src/serial_data_channel/serial_data_channel.cpp.i

src/serial_data_channel/serial_data_channel.s: src/serial_data_channel/serial_data_channel.cpp.s

.PHONY : src/serial_data_channel/serial_data_channel.s

# target to generate assembly for a file
src/serial_data_channel/serial_data_channel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/serial_data_channel/serial_data_channel.cpp.s
.PHONY : src/serial_data_channel/serial_data_channel.cpp.s

src/serial_data_channel/serial_data_manager.o: src/serial_data_channel/serial_data_manager.cpp.o

.PHONY : src/serial_data_channel/serial_data_manager.o

# target to build an object file
src/serial_data_channel/serial_data_manager.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/serial_data_channel/serial_data_manager.cpp.o
.PHONY : src/serial_data_channel/serial_data_manager.cpp.o

src/serial_data_channel/serial_data_manager.i: src/serial_data_channel/serial_data_manager.cpp.i

.PHONY : src/serial_data_channel/serial_data_manager.i

# target to preprocess a source file
src/serial_data_channel/serial_data_manager.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/serial_data_channel/serial_data_manager.cpp.i
.PHONY : src/serial_data_channel/serial_data_manager.cpp.i

src/serial_data_channel/serial_data_manager.s: src/serial_data_channel/serial_data_manager.cpp.s

.PHONY : src/serial_data_channel/serial_data_manager.s

# target to generate assembly for a file
src/serial_data_channel/serial_data_manager.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/serial_data_channel/serial_data_manager.cpp.s
.PHONY : src/serial_data_channel/serial_data_manager.cpp.s

src/sora/sora_client.o: src/sora/sora_client.cpp.o

.PHONY : src/sora/sora_client.o

# target to build an object file
src/sora/sora_client.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/sora/sora_client.cpp.o
.PHONY : src/sora/sora_client.cpp.o

src/sora/sora_client.i: src/sora/sora_client.cpp.i

.PHONY : src/sora/sora_client.i

# target to preprocess a source file
src/sora/sora_client.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/sora/sora_client.cpp.i
.PHONY : src/sora/sora_client.cpp.i

src/sora/sora_client.s: src/sora/sora_client.cpp.s

.PHONY : src/sora/sora_client.s

# target to generate assembly for a file
src/sora/sora_client.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/sora/sora_client.cpp.s
.PHONY : src/sora/sora_client.cpp.s

src/sora/sora_server.o: src/sora/sora_server.cpp.o

.PHONY : src/sora/sora_server.o

# target to build an object file
src/sora/sora_server.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/sora/sora_server.cpp.o
.PHONY : src/sora/sora_server.cpp.o

src/sora/sora_server.i: src/sora/sora_server.cpp.i

.PHONY : src/sora/sora_server.i

# target to preprocess a source file
src/sora/sora_server.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/sora/sora_server.cpp.i
.PHONY : src/sora/sora_server.cpp.i

src/sora/sora_server.s: src/sora/sora_server.cpp.s

.PHONY : src/sora/sora_server.s

# target to generate assembly for a file
src/sora/sora_server.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/sora/sora_server.cpp.s
.PHONY : src/sora/sora_server.cpp.s

src/sora/sora_session.o: src/sora/sora_session.cpp.o

.PHONY : src/sora/sora_session.o

# target to build an object file
src/sora/sora_session.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/sora/sora_session.cpp.o
.PHONY : src/sora/sora_session.cpp.o

src/sora/sora_session.i: src/sora/sora_session.cpp.i

.PHONY : src/sora/sora_session.i

# target to preprocess a source file
src/sora/sora_session.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/sora/sora_session.cpp.i
.PHONY : src/sora/sora_session.cpp.i

src/sora/sora_session.s: src/sora/sora_session.cpp.s

.PHONY : src/sora/sora_session.s

# target to generate assembly for a file
src/sora/sora_session.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/sora/sora_session.cpp.s
.PHONY : src/sora/sora_session.cpp.s

src/ssl_verifier.o: src/ssl_verifier.cpp.o

.PHONY : src/ssl_verifier.o

# target to build an object file
src/ssl_verifier.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/ssl_verifier.cpp.o
.PHONY : src/ssl_verifier.cpp.o

src/ssl_verifier.i: src/ssl_verifier.cpp.i

.PHONY : src/ssl_verifier.i

# target to preprocess a source file
src/ssl_verifier.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/ssl_verifier.cpp.i
.PHONY : src/ssl_verifier.cpp.i

src/ssl_verifier.s: src/ssl_verifier.cpp.s

.PHONY : src/ssl_verifier.s

# target to generate assembly for a file
src/ssl_verifier.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/ssl_verifier.cpp.s
.PHONY : src/ssl_verifier.cpp.s

src/util.o: src/util.cpp.o

.PHONY : src/util.o

# target to build an object file
src/util.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/util.cpp.o
.PHONY : src/util.cpp.o

src/util.i: src/util.cpp.i

.PHONY : src/util.i

# target to preprocess a source file
src/util.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/util.cpp.i
.PHONY : src/util.cpp.i

src/util.s: src/util.cpp.s

.PHONY : src/util.s

# target to generate assembly for a file
src/util.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/util.cpp.s
.PHONY : src/util.cpp.s

src/watchdog.o: src/watchdog.cpp.o

.PHONY : src/watchdog.o

# target to build an object file
src/watchdog.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/watchdog.cpp.o
.PHONY : src/watchdog.cpp.o

src/watchdog.i: src/watchdog.cpp.i

.PHONY : src/watchdog.i

# target to preprocess a source file
src/watchdog.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/watchdog.cpp.i
.PHONY : src/watchdog.cpp.i

src/watchdog.s: src/watchdog.cpp.s

.PHONY : src/watchdog.s

# target to generate assembly for a file
src/watchdog.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/watchdog.cpp.s
.PHONY : src/watchdog.cpp.s

src/websocket.o: src/websocket.cpp.o

.PHONY : src/websocket.o

# target to build an object file
src/websocket.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/websocket.cpp.o
.PHONY : src/websocket.cpp.o

src/websocket.i: src/websocket.cpp.i

.PHONY : src/websocket.i

# target to preprocess a source file
src/websocket.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/websocket.cpp.i
.PHONY : src/websocket.cpp.i

src/websocket.s: src/websocket.cpp.s

.PHONY : src/websocket.s

# target to generate assembly for a file
src/websocket.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/momo.dir/build.make CMakeFiles/momo.dir/src/websocket.cpp.s
.PHONY : src/websocket.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... momo"
	@echo "... src/ayame/ayame_client.o"
	@echo "... src/ayame/ayame_client.i"
	@echo "... src/ayame/ayame_client.s"
	@echo "... src/mac_helper/mac_capturer.o"
	@echo "... src/mac_helper/mac_capturer.i"
	@echo "... src/mac_helper/mac_capturer.s"
	@echo "... src/mac_helper/macos_version.o"
	@echo "... src/mac_helper/macos_version.i"
	@echo "... src/mac_helper/macos_version.s"
	@echo "... src/mac_helper/objc_codec_factory_helper.o"
	@echo "... src/mac_helper/objc_codec_factory_helper.i"
	@echo "... src/mac_helper/objc_codec_factory_helper.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/momo_version.o"
	@echo "... src/momo_version.i"
	@echo "... src/momo_version.s"
	@echo "... src/p2p/p2p_server.o"
	@echo "... src/p2p/p2p_server.i"
	@echo "... src/p2p/p2p_server.s"
	@echo "... src/p2p/p2p_session.o"
	@echo "... src/p2p/p2p_session.i"
	@echo "... src/p2p/p2p_session.s"
	@echo "... src/p2p/p2p_websocket_session.o"
	@echo "... src/p2p/p2p_websocket_session.i"
	@echo "... src/p2p/p2p_websocket_session.s"
	@echo "... src/rtc/device_video_capturer.o"
	@echo "... src/rtc/device_video_capturer.i"
	@echo "... src/rtc/device_video_capturer.s"
	@echo "... src/rtc/h264_format.o"
	@echo "... src/rtc/h264_format.i"
	@echo "... src/rtc/h264_format.s"
	@echo "... src/rtc/momo_video_decoder_factory.o"
	@echo "... src/rtc/momo_video_decoder_factory.i"
	@echo "... src/rtc/momo_video_decoder_factory.s"
	@echo "... src/rtc/momo_video_encoder_factory.o"
	@echo "... src/rtc/momo_video_encoder_factory.i"
	@echo "... src/rtc/momo_video_encoder_factory.s"
	@echo "... src/rtc/native_buffer.o"
	@echo "... src/rtc/native_buffer.i"
	@echo "... src/rtc/native_buffer.s"
	@echo "... src/rtc/peer_connection_observer.o"
	@echo "... src/rtc/peer_connection_observer.i"
	@echo "... src/rtc/peer_connection_observer.s"
	@echo "... src/rtc/rtc_connection.o"
	@echo "... src/rtc/rtc_connection.i"
	@echo "... src/rtc/rtc_connection.s"
	@echo "... src/rtc/rtc_manager.o"
	@echo "... src/rtc/rtc_manager.i"
	@echo "... src/rtc/rtc_manager.s"
	@echo "... src/rtc/rtc_ssl_verifier.o"
	@echo "... src/rtc/rtc_ssl_verifier.i"
	@echo "... src/rtc/rtc_ssl_verifier.s"
	@echo "... src/rtc/scalable_track_source.o"
	@echo "... src/rtc/scalable_track_source.i"
	@echo "... src/rtc/scalable_track_source.s"
	@echo "... src/rtc/screen_video_capturer.o"
	@echo "... src/rtc/screen_video_capturer.i"
	@echo "... src/rtc/screen_video_capturer.s"
	@echo "... src/sdl_renderer/sdl_renderer.o"
	@echo "... src/sdl_renderer/sdl_renderer.i"
	@echo "... src/sdl_renderer/sdl_renderer.s"
	@echo "... src/serial_data_channel/serial_data_channel.o"
	@echo "... src/serial_data_channel/serial_data_channel.i"
	@echo "... src/serial_data_channel/serial_data_channel.s"
	@echo "... src/serial_data_channel/serial_data_manager.o"
	@echo "... src/serial_data_channel/serial_data_manager.i"
	@echo "... src/serial_data_channel/serial_data_manager.s"
	@echo "... src/sora/sora_client.o"
	@echo "... src/sora/sora_client.i"
	@echo "... src/sora/sora_client.s"
	@echo "... src/sora/sora_server.o"
	@echo "... src/sora/sora_server.i"
	@echo "... src/sora/sora_server.s"
	@echo "... src/sora/sora_session.o"
	@echo "... src/sora/sora_session.i"
	@echo "... src/sora/sora_session.s"
	@echo "... src/ssl_verifier.o"
	@echo "... src/ssl_verifier.i"
	@echo "... src/ssl_verifier.s"
	@echo "... src/util.o"
	@echo "... src/util.i"
	@echo "... src/util.s"
	@echo "... src/watchdog.o"
	@echo "... src/watchdog.i"
	@echo "... src/watchdog.s"
	@echo "... src/websocket.o"
	@echo "... src/websocket.i"
	@echo "... src/websocket.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

